[openai]
api_key = "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"
model_function = "gpt-3.5-turbo-0613"
temperature = 0

[supabase]
table_name = "documents"
url = "https://wclrnqqdaovfrchhhlzj.supabase.co"
api_key_normal = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjbHJucXFkYW92ZnJjaGhobHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDY2Nzk2MjYsImV4cCI6MjAyMjI1NTYyNn0.HCNQ3dP1UN7_SphNy9zNfHit7V0RDrd6Uu9HPDm81B8"
api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjbHJucXFkYW92ZnJjaGhobHpqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNjY3OTYyNiwiZXhwIjoyMDIyMjU1NjI2fQ.5QY5Ik-qmkhJPDMPvuOJjXaHN0AA2t_E-WV4Kn0IxJ0"


[google]
api_key = "AIzaSyDGy9el4sZshs5guM-nlI3-v3rqd-CpowE"
cse_key = "h1181f1fb03db14fd8"

[scraper]
header_useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36"

[tavily]
api_key = "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"

[streamlit]
page_config_title = "FlowGenius"
page_config_icon = "🧠"
page_config_layout = "wide"
page_config_sidebar = "collapsed"

[serpapi]
api_key = "ab850e356934acac3e85d03eff1f4ca2d1bae552153d7ba35c316e75af178217"